stages:
    # - diff: "fast_carpenter.Define"
    - histogram: "fast_carpenter.BinnedDataframe"

diff:
    variables:
        - diff_emu: "l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.iet - l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.et"

histogram:
    binning:
        # - {in: diff_emu, bins: {edges: [-100, -50, -20, 0, 20, 50, 100]}}
        - {in: "l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.iet", out: iet, bins: {edges: [0, 200, 400, 700, 1000]}}
        - {in: "l1CaloTowerEmuTree.L1CaloTowerTree.L1CaloTower.iet", out: emu_iet, bins: {edges: [0, 200, 400, 700, 1000]}}
